image: elixir

before_script:
  - mix local.rebar --force
  - mix local.hex --force

lake:
  script:
  - cd lake/
  - rebar3 ct
  - rebar3 fmt --check

lake_house:
  script:
  - cd lake_house
  - mix deps.get
  - mix test
  - mix format --check-formatted
