image: elixir

services:
  - name: registry.gitlab.com/evnu/lake/rabbitmq_with_streams
    alias: rabbitmq

before_script:
  - mix local.rebar --force

lake:
  variables:
    RABBITMQ_HOST: rabbitmq
  script:
  - rebar3 ct
  - rebar3 eunit
  - rebar3 fmt --check
